apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2VybmFtZQ== #mongousername
  MONGO_INITDB_ROOT_PASSWORD: TmFnYXJyb1Bhc3N3b3Jk #NagarroPassword
